package bm.minecraft.the.end.plus;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/** A bounded, backed-up reset of a Paper 26.3 dimension, never the world root. */
final class BmMinecraftTheEndPlusResetFiles {
    static final Path DRAGON_FIGHT = Path.of("data", "minecraft", "ender_dragon_fight.dat");
    private static final Pattern EXTERNAL_CHUNK = Pattern.compile("c\\.(-?\\d+)\\.(-?\\d+)\\.mcc");
    private final Path dimension;
    private final Path backup;
    private final List<Path> originals;
    private boolean backupComplete;
    private boolean modified;

    BmMinecraftTheEndPlusResetFiles(Path dimension, Path backup) throws IOException {
        this.dimension = dimension.toRealPath();
        this.backup = canonicalDestination(backup);
        if (this.backup.startsWith(this.dimension)) {
            throw new IOException("Backup must be outside the End dimension: " + backup);
        }
        // Refuse legacy/unknown layouts instead of deleting terrain but retaining the battle.
        requireRegularFile(this.dimension.resolve(DRAGON_FIGHT));
        this.originals = selectFiles(this.dimension);
    }

    static List<Path> selectFiles(Path dimension) throws IOException {
        List<Path> files = new ArrayList<>();
        for (String type : List.of("region", "entities", "poi")) {
            Path directory = dimension.resolve(type);
            if (!Files.exists(directory, LinkOption.NOFOLLOW_LINKS)) {
                continue;
            }
            if (Files.isSymbolicLink(directory) || !Files.isDirectory(directory)
                    || !directory.toRealPath().equals(dimension.toRealPath().resolve(type))) {
                throw new IOException("Not a regular region directory: " + directory);
            }
            try (Stream<Path> entries = Files.list(directory)) {
                for (Path entry : entries.toList()) {
                    if (isCentralFile(entry.getFileName().toString())) {
                        requireRegularFile(entry);
                        files.add(dimension.relativize(entry));
                    }
                }
            }
        }
        for (Path relative : List.of(DRAGON_FIGHT, Path.of(DRAGON_FIGHT + "_old"))) {
            Path file = dimension.resolve(relative);
            checkParents(dimension, relative);
            if (Files.exists(file, LinkOption.NOFOLLOW_LINKS)) {
                requireRegularFile(file);
                files.add(relative);
            }
        }
        return List.copyOf(files);
    }

    static boolean isCentralFile(String name) {
        if (List.of("r.-1.-1.mca", "r.-1.0.mca", "r.0.-1.mca", "r.0.0.mca").contains(name)) {
            return true;
        }
        var match = EXTERNAL_CHUNK.matcher(name);
        if (!match.matches()) {
            return false;
        }
        try {
            int x = Integer.parseInt(match.group(1));
            int z = Integer.parseInt(match.group(2));
            return x >= -32 && x < 32 && z >= -32 && z < 32;
        } catch (NumberFormatException ignored) {
            return false;
        }
    }

    void backupAndDelete() throws IOException {
        Files.createDirectories(backup);
        Files.writeString(backup.resolve("dimension.txt"), dimension.toString());
        for (Path relative : originals) {
            Path target = backup.resolve(relative);
            Files.createDirectories(target.getParent());
            Files.copy(dimension.resolve(relative), target);
        }
        backupComplete = true;
        status("prepared");
        modified = true;
        status("resetting");
        for (Path relative : originals) {
            Files.delete(dimension.resolve(relative));
        }
        if (!selectFiles(dimension).isEmpty()) {
            throw new IOException("Central region or dragon fight files remain after deletion");
        }
    }

    void rollback() throws IOException {
        if (!backupComplete || !modified) {
            return;
        }
        // Also remove any central files generated by a failed world load.
        for (Path relative : selectFiles(dimension)) {
            Files.delete(dimension.resolve(relative));
        }
        for (Path relative : originals) {
            Path target = dimension.resolve(relative);
            Files.createDirectories(target.getParent());
            Files.copy(backup.resolve(relative), target, StandardCopyOption.REPLACE_EXISTING);
        }
        status("rolled-back");
    }

    void status(String value) throws IOException {
        Files.writeString(backup.resolve("status.txt"), value);
    }

    private static void checkParents(Path root, Path relative) throws IOException {
        Path current = root;
        for (Path part : relative.getParent()) {
            current = current.resolve(part);
            if (Files.isSymbolicLink(current)
                    || (Files.exists(current) && !current.toRealPath()
                    .equals(root.toRealPath().resolve(root.relativize(current))))) {
                throw new IOException("Linked directory in reset path: " + current);
            }
        }
    }

    private static void requireRegularFile(Path file) throws IOException {
        if (!Files.isRegularFile(file, LinkOption.NOFOLLOW_LINKS)) {
            throw new IOException("Missing or unsafe reset file: " + file);
        }
    }

    private static Path canonicalDestination(Path path) throws IOException {
        Path absolute = path.toAbsolutePath().normalize();
        Path ancestor = absolute;
        while (!Files.exists(ancestor)) {
            ancestor = ancestor.getParent();
            if (ancestor == null) {
                throw new IOException("No existing ancestor for backup: " + path);
            }
        }
        return ancestor.toRealPath().resolve(ancestor.relativize(absolute)).normalize();
    }
}
